project:
  type: website
  output-dir: _site

date: last-modified
date-format: D MMMM, YYYY

website:
  title: "Reproducible reports<br>with Quarto"
  favicon: images/logo_no_text_transparent.png
  page-footer:
    left: "<https://digitalskillscatalyst.ac.uk/>."
  navbar:
    logo: images/logo_transparent_background.png
    background: primary
    site-url: https://ukri-digital-research-skills-catalyst.github.io/quarto-intro/
    repo-url: https://ukri-digital-research-skills-catalyst.github.io/quarto-intro/
    page-navigation: true
    search: true
    left:
      - text: "Welcome!"
        file: index.qmd
      - text: "Before the course"
        file:  before.qmd
      - text: "Materials"
        file:  materials.qmd

execute:
  echo: true
  warning: false
  output: true
  error: true
  collapse: true
  freeze: auto

engine: knitr

format:
  html:
    css: styles.css
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/ukri-digital-research-skills-catalyst\.github\.io\/quarto-intro'
    code-copy: true
    code-link: true
    code-overflow: wrap
    code-line-numbers: false
    toc: true
    toc-depth: 4
    fig-format: svg
    lightbox: true
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

metadata-files:
  - _downlit.yml

fig-dpi: 600

bibliography: references.bib

editor: source